name: Releases Builder
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.HUB_DOCKER_USERNAME }}/glibc

      -
        name: Release version
        id: release_version
        run: |
          glibc_version=$(sed -n "s/ENV\sVERSION_GLIBC=\(.*\)/\1/gp" Dockerfile)
          echo "glibc_version=$glibc_version" >> $GITHUB_ENV

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login to Aliyun
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_DOCKER_USERNAME }}
          password: ${{ secrets.HUB_DOCKER_PASSWORD }}

      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            GLIBC_VERSION=${{ env.glibc_version }}
          tags: |
            ${{ secrets.HUB_DOCKER_USERNAME }}/glibc:${{ env.glibc_version }}
            ${{ secrets.HUB_DOCKER_USERNAME }}/glibc:latest
            registry.cn-hangzhou.aliyuncs.com/${{ secrets.HUB_DOCKER_USERNAME }}/glibc:${{ env.glibc_version }}
            registry.cn-hangzhou.aliyuncs.com/${{ secrets.HUB_DOCKER_USERNAME }}/glibc:latest
          labels: ${{ steps.meta.outputs.labels }}
